import { Metadata } from "next";
import { Dancing_Script, Inter } from "next/font/google";
import "the-new-css-reset/css/reset.css";
import Footer from "./components/footer";
import Header from "./components/header";
import "./globals.css";
import Providers from "./providers";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});
const dancingScript = Dancing_Script({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dancing",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${dancingScript.variable} ${inter.variable}`}>
      <body className="font-inter">
        <Header />

        <Providers>{children}</Providers>

        <Footer />
      </body>
    </html>
  );
}
