import type { Metadata } from "next";
import { Inter, Dancing_Script } from "next/font/google";
import "the-new-css-reset/css/reset.css";
import "./globals.css";

export const inter = Inter({ subsets: ["latin"], display: "swap", variable: '--font-inter'});
export const dancingScript = Dancing_Script({ subsets: ["latin"], display: "swap", variable: '--font-dancing'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${dancingScript.variable} ${inter.variable}`}>
      <body className='bg-neutral-100 font-inter'>
        {children}
      </body>
    </html>
  );
}
